GU-99/grow-up-fe

- src/layouts/DefaultLayout.tsx
- src/layouts/ProjectLayout.tsx
- src/layouts/SettingLayout.tsx
- src/layouts/TeamLayout.tsx
- src/main.tsx
- src/pages/ErrorPage.tsx
- src/pages/NotFoundPage.tsx
- src/pages/project/CalendarPage.tsx
- src/pages/project/KanbanPage.tsx
- src/pages/setting/TeamSettingPage.tsx
- src/pages/setting/UserSettingPage.tsx
- src/pages/team/TeamPage.tsx
- src/pages/user/SearchIdPage.tsx
- src/pages/user/SearchPasswordPage.tsx
- src/pages/user/SignInPage.tsx
- src/pages/user/SignUpPage.tsx
- src/routes/AfterLoginRoute.tsx
- src/routes/BeforeLoginRoute.tsx
- src/routes/MainRouter.tsx
- tsconfig.json
- vite.config.ts
> 페이지 라우터 설정하기

- src/globals.css
- src/index.css
- src/main.tsx
- tailwind.config.js
#13 Tailwind CSS 속성 커스텀
1. [spacing customizing]( https://tailwindcss.com/docs/customizing-spacing) + 각 속성별 customizing
2. [tailwind 유틸리티 기본 구성](https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/config.full.js)
2. [Add Google Font to Tailwind - React](https://medium.com/@pradipdev/add-google-font-to-tailwind-react-4178d5d2b04f)
3. [comento - Tailwind CSS 설정에서 규칙까지](https://developer.comento.kr/post/frontend-tailwind-css-24-04-01)
4. [Tailwind CSS에서 혼란을 방지하기 위한 5가지 모법 사례](https://velog.io/@lky5697/5-best-practices-for-preventing-chaos-in-tailwind-css)
한 가지 고민 사항이 있습니다. 
전역 변수에 정의한 contents size 주석 부분에 있는 내용들은 box model 설정과 관련된 내용인데요. spacing을 저희의 편의에 맞춰 0.1 단위로 0~40rem까지 설정했기 때문에 별도로 tailwind 유틸리티 클래스를 확장하지 않아도 원하는 크기로 작성할 수 있다고 …
> Config: #13 Tailwind CSS 속성 커스텀하기

- src/globals.css
- src/layouts/DefaultLayout.tsx
- src/layouts/ProjectLayout.tsx
- tailwind.config.js
#21 특정 프로젝트 관리 UI 작성
1. [Inpa: 스크롤바 스타일링 총정리](https://inpa.tistory.com/entry/CSS-%F0%9F%8C%9F-%EC%8A%A4%ED%81%AC%EB%A1%A4-%EB%B0%94Scrollbar-%EA%BE%B8%EB%AF%B8%EA%B8%B0-%EC%86%8D%EC%84%B1-%EC%B4%9D%EC%A0%95%EB%A6%AC)
2. [TailwindCSS 공식문서:  resuing styles - @apply](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply)
> UI: #21 프로젝트 레이아웃 작성

- src/components/sidebar/ListProject.tsx
- src/layouts/page/ProjectLayout.tsx
> UI: #24 상태 추가 컴포넌틑 모달 적용

- src/pages/user/SignInPage.tsx
#49 로그인 페이지 import 오류 수정
conflict 처리 시 오류로 페이지가 렌더링되지 않는 버그가 발생하여 수정했습니다.
> Fix: #49 로그인 페이지 import 오류 수정

- src/globals.css
#55 스크롤바 UI 변경
**Before**
**After**
> UI: #55 스크롤바 UI 변경

- src/components/modal/task/CreateModalTask.tsx
- src/components/modal/task/ModalTaskForm.tsx
- src/components/modal/task/UpdateModalTask.tsx
- src/layouts/page/ProjectLayout.tsx
- src/pages/project/CalendarPage.tsx
- src/types/TaskType.tsx
> UI: #57 프로젝트 레이아웃 UI 변경

- .vscode/extensions.json
> Config: #76 VSCode 확장앱 추가

- src/components/modal/team/ModalTeamForm.tsx
> Fix: 모든 페이지 관리 팀 모달 props 오류 수정

- .eslintrc.cjs
- src/components/modal/task/ModalTaskForm.tsx
- src/components/user/auth-form/LinkContainer.tsx
- src/components/user/auth-form/ProfileImageContainer.tsx
- src/constants/formValidationRules.ts
- src/constants/regex.ts
- src/constants/settings.ts
- src/utils/reduceImageSize.ts
#63 할일 등록 모달 UI 작성 및 기능 개발
**input file 설정  참고자료**
1. [input: multiple Attribute](https://www.w3schools.com/tags/att_input_multiple.asp)
2. [input: hidden Attribute](https://www.w3schools.com/tags/att_input_type_hidden.asp)
**DOM 파일 업로드 관련 참고자료**
1. [MDN: Blob](https://developer.mozilla.org/ko/docs/Web/API/Blob)
2. [MDN: File](https://developer.mozilla.org/ko/docs/Web/API/File)
3. [MDN: FileList](https://developer.mozilla.org/ko/docs/Web/API/FileList)
4. [MDN: 웹 어플리케이션에서 파일 사용하기](https://developer.mozilla.org/ko/docs/Web/API/File_API/Using_files_from_web_applications)
> Feat: #63 할일 등록 모달 DnD 파일 첨부 기능 추가

- package.json
- src/components/modal/task/ModalTaskForm.tsx
- src/hooks/errorHandler.ts
- src/hooks/query/queryClient.ts
- src/hooks/query/useTaskQuery.ts
- src/hooks/useAxios.ts
- src/main.tsx
- src/mocks/handlers.ts
- src/mocks/mockData.ts
- src/mocks/services/taskServiceHandler.ts
- src/pages/project/CalendarPage.tsx
- src/pages/project/KanbanPage.tsx
- src/services/taskService.ts
- src/types/ProjectStatusType.tsx
- src/types/TaskType.tsx
- yarn.lock
- related to #89 
사실.. 할일 상세 모달을 작업하려고 시작한 브랜치인데, 작업을 진행하다보니 React Query 설정과 데이터 더미 처리 방식을 수정하는 내용이 되어버렸네요😓 다음엔 더 세분화 해서 작업하겠습니다
추가적으로 기존에 더미로만 작업하던 내용을 react query로 조금씩 변경하면서, 기존 UI들이 사용하던 데이터가 변경되어 이상하게 보이는 부분이 생길테지만, 아직 진행중인 내용이니 놀라지 않으셔도 괜찮아요🙇‍♂️
> Feat: React Query 기본 환경 설정 & 상태별 프로젝트 일정 전체 조회 API 처리 추가

- src/components/common/Spinner.tsx
- src/components/modal/project-status/ModalProjectStatusForm.tsx
- src/components/modal/task/ModalTaskForm.tsx
- src/hooks/query/useStatusQuery.ts
- src/mocks/handlers.ts
- src/mocks/services/statusServiceHandler.ts
- src/services/statusService.ts
- close #98 
※ 대기 화면을 보여주기 위해 MSW에서 response를 3초 지연하도록 만들어 찍은 이미지입니다.
※ Spinner만 돌아가는게 뭔가 휑한 느낌이 조금 있네요😓 더 좋은 방법이 있으면 추천 받습니다!
> Feat: #98 프로젝트 상태 목록 조회 API 기능 구현

- src/components/modal/project-status/UpdateModalProjectStatus.tsx
- src/hooks/query/useStatusQuery.ts
- src/mocks/services/statusServiceHandler.ts
- src/services/statusService.ts
- close #102 
아래의 칸반의 상태 색상이나 이름이 변경되지 않는 이유는 아직 고정된 더미 데이터를 통해 보여주고 있기 때문입니다. 금방 변경될 예정입니다🙇‍♂️
> Feat: #102 프로젝트 상태 변경 API를 이용하여 상태 변경 기능 구현

- src/components/modal/ModalFormButton.tsx
- src/components/modal/project-status/ModalProjectStatusForm.tsx
- src/layouts/ModalLayout.tsx
> UI: #107 모달 레이아웃 UI 수정

- src/components/sidebar/ListTeam.tsx
- src/hooks/query/useTeamQuery.ts
- src/layouts/page/SettingLayout.tsx
- src/layouts/page/TeamSettingLayout.tsx
- src/mocks/mockData.ts
- src/mocks/services/userServiceHandler.ts
- src/pages/setting/TeamInvitedPage.tsx
- src/pages/setting/TeamJoinedPage.tsx
- src/pages/setting/TeamSettingPage.tsx
- src/pages/team/TeamPage.tsx
- src/routes/MainRouter.tsx
- src/services/userService.ts
- src/types/TeamType.tsx
- close #85 
스크롤 대신 overflow 된 부분은 ... 으로 대체 함.
> UI: #85 모든 프로젝트 및 팀 설정 페이지 UI 변경

- src/hooks/query/useStatusQuery.ts
- src/mocks/mockHash.ts
- src/mocks/services/statusServiceHandler.ts
- src/mocks/services/taskServiceHandler.ts
> Fix: #117 상태 추가 후 상태 순서 변경시 발생하는 에러 해결

- src/components/sidebar/ListSidebar.tsx
- src/components/task/kanban/TaskItem.tsx
- src/components/task/kanban/TaskItemList.tsx
- src/layouts/page/ProjectLayout.tsx
- src/layouts/page/SettingLayout.tsx
- src/layouts/page/TeamLayout.tsx
- src/mocks/services/taskServiceHandler.ts
- src/pages/project/CalendarPage.tsx
- src/pages/project/KanbanPage.tsx
- close #122 
**해결하기 전 문제의 칸반 보드**
**해결된 칸반 보드**
> Fix: #122 칸반 보드 UI가 정해진 범위를 넘어가는 문제 해결

- src/components/common/CustomMarkdown.tsx
- src/components/modal/ModalFormButton.tsx
- src/components/task/kanban/TaskItem.tsx
- src/components/task/kanban/TaskItemList.tsx
- src/hooks/query/useStatusQuery.ts
- src/mocks/mockData.ts
- src/pages/project/CalendarPage.tsx
- src/pages/project/KanbanPage.tsx
- related to #89 
일정 목록 조회 API 수정을 고민하고 있고, 프로젝트원 목록 조회 API를 개발중에 있어 추가/변경되는대로 이어서 작업하도록 하겠습니다. 일단은 UI만 작업해둔 상태입니다.
> UI: #89 일정 상세보기 모달 UI 작성

- src/components/common/FileDropZone.tsx
- src/components/common/MarkdownEditor.tsx
- src/components/common/PeriodDateInput.tsx
- src/components/common/StatusRadio.tsx
- src/components/modal/task/ModalTaskForm.tsx
- src/types/FileType.tsx
- related to #127 
수행자 검색을 컴포넌트로 분리하기에 앞서 분량이 많아질 것을 고려해 한 번 합치려고 합니다. 파일명, props 설정과 props명 등이 적절한지 확인 부탁드립니다.
> UI: #127 일정 등록 입력 양식들을 컴포넌트로 분리

- src/components/modal/task/DetailModalTask.tsx
- src/hooks/query/useTaskQuery.ts
- src/mocks/mockData.ts
- src/mocks/services/taskServiceHandler.ts
- src/services/taskService.ts
- src/types/FileType.tsx
- src/types/TaskType.tsx
> Feat: #135 일정 파일 목록 조회 기능 추가

- src/components/common/CustomMarkdown.tsx
- close #140
[MDN \<a>: 보안과 개인정보](https://developer.mozilla.org/ko/docs/Web/HTML/Element/a#%EB%B3%B4%EC%95%88%EA%B3%BC_%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4)
> Feat: #140 마크다운 커스텀 a태그 속성 수정

- src/constants/formValidationRules.ts
- src/mocks/mockData.ts
- src/mocks/services/authServiceHandler.ts
- src/pages/setting/UserPasswordSettingPage.tsx
- src/services/authService.ts
- src/types/UserType.tsx
> Feat: #144 비밀번호 변경 기능 구현

- src/components/common/FileDropZone.tsx
- src/components/modal/task/ModalTaskForm.tsx
- src/components/modal/task/UpdateModalTask.tsx
- src/hooks/query/useTaskQuery.ts
- src/mocks/services/taskServiceHandler.ts
- src/services/taskService.ts
- src/types/TaskType.tsx
- related to #115 
일정 파일 업로드, 다운로드, 삭제 등의 API가 아직 정리되지 않아서, 일단은 파일 가시성 내용만 추가하고 나중에 이어서 기능을 붙이려고 생각하고 있습니다.
> UI: 파일 드래그 앤 드롭시 영역 스타일 가시성 스타일 추가

- src/components/modal/task/UpdateModalTask.tsx
- src/hooks/query/useTaskQuery.ts
- src/mocks/services/taskServiceHandler.ts
- src/services/taskService.ts
- src/types/TaskType.tsx
- close #149 
**수행자 추가 에러시 화면**
**수행자 추가 성공시 화면**
> Feat: #149 일정 수정 모달 수행자 추가 기능 구현

- src/components/modal/task/UpdateModalTask.tsx
- src/hooks/query/useTaskQuery.ts
- src/mocks/services/taskServiceHandler.ts
- src/services/taskService.ts
> Feat: #156 일정 수정 모달 일정 정보 변경 기능 구현

- src/components/common/StatusRadio.tsx
- src/components/modal/task/UpdateModalTask.tsx
- src/hooks/query/useTaskQuery.ts
- src/mocks/services/taskServiceHandler.ts
- src/services/taskService.ts
- src/types/TaskType.tsx
- close #163 
기존에 있던 타입을 수정하지 않고, 일정 수정 모달을 위한 타입을 새로 정의하는 것으로 다른 코드에 미칠 수 있는 영향을 최소화 했습니다.
**에러 수정 전**
**에러 수정 후**
※ radio 선택 표시는 정확한 확인을 위해 임시로 CSS를 지운 상태입니다. 실제 화면에선 파란색 선택 내역이 보이지 않습니다.
> Fix: #163 일정 수정 모달에서 상태 선택 정보가 사라지는 문제 해결

- src/components/modal/project-status/UpdateModalProjectStatus.tsx
- src/hooks/query/queryClient.ts
- src/hooks/query/useStatusQuery.ts
- src/hooks/query/useTaskQuery.ts
- src/mocks/services/statusServiceHandler.ts
- src/services/statusService.ts
> Feat: #169 상태 삭제 기능 구현

- src/components/modal/task/DetailModalTask.tsx
- src/mocks/mockData.ts
- src/mocks/services/taskServiceHandler.ts
- src/types/FileType.tsx
> Formatting: #183 파일 목록 조회 API의 응답 데이터 구조 변경 반영

- src/components/sidebar/ListTeam.tsx
- src/layouts/page/TeamLayout.tsx
- src/pages/team/TeamPage.tsx
> Fix: #214 프로젝트 목록 및 팀 목록 쿼리로 변경

- src/components/modal/project-status/CreateModalProjectStatus.tsx
- src/hooks/query/useProjectQuery.ts
- src/hooks/query/useUserQuery.ts
- src/layouts/page/TeamLayout.tsx
- src/mocks/services/projectServiceHandler.ts
- src/pages/team/TeamPage.tsx
- src/services/projectService.ts
* close #210 
프로젝트 삭제
https://github.com/user-attachments/assets/0d0683bf-7971-43d7-a22b-2939865d7676
> Feat: #210 프로젝트 삭제 기능 추가

- src/routes/MainRouter.tsx
> Fix: #216 home 페이지로 이동시 teams 페이지로 리다이렉션

- src/components/modal/project/CreateModalProject.tsx
- src/components/modal/project/ModalProjectForm.tsx
- src/constants/formValidationRules.ts
- src/constants/role.ts
- src/pages/team/TeamPage.tsx
- src/types/ProjectType.tsx
* close #199 
프로젝트 권한
프로젝트 생성 UI
> UI:#199 프로젝트 생성 UI 구현

- src/mocks/mockAPI.ts
- src/mocks/services/projectServiceHandler.ts
- src/mocks/services/statusServiceHandler.ts
- src/mocks/services/taskServiceHandler.ts
- close #224 
어제 taskServiceHandler에서 모든 처리에 대해 프로젝트 접근 권한이 있어야 처리되도록 만들었지만, 생각해보니 프로젝트 권한이 없더라도 팀에 속한 유저는 프로젝트 정보 조회가 가능해야 합니다. 그래서 조회성 로직에는 프로젝트 접근 권한이 아니라 팀 접근 권한이 있는가로 추가적으로 수정했습니다.
> Refactor: #224 MSW 처리중 StatusService, ProjectService 기능 리팩토링

- src/mocks/services/teamServiceHandler.ts
- src/pages/setting/TeamJoinedPage.tsx
> Fix: #245 accesstoken 더미 데이터를 유저 데이터로 수정

- src/mocks/services/authServiceHandler.ts
- src/pages/setting/UserPasswordSettingPage.tsx
- src/services/authService.ts
- src/services/userService.ts
- close #231 
- close #146 
- 동작 과정은 위 이슈의 PR에 올린 내용과 동일합니다.
> Chore: #231 이메일 인증 관련 코드 검토 및 주석 제거

- src/components/modal/project/UpdateModalProject.tsx
- src/hooks/query/useProjectQuery.ts
- src/mocks/mockAPI.ts
- src/mocks/services/projectServiceHandler.ts
- src/services/projectService.ts
> Feat: #253 프로젝트 팀원 삭제 추가

- src/components/common/RoleTooltip.tsx
- src/constants/role.ts
> Formatting: #257 권한 설명 변경

- src/components/common/UserRoleSelectBox.tsx
- src/components/modal/team/ModalTeamForm.tsx
- src/constants/role.ts
- src/mocks/services/userServiceHandler.ts
> Feat: #261 유저 전체 검색 mswHandler 추가 & 팀 생성 시 HEAD 권한 삭제

- src/mocks/services/authServiceHandler.ts
- src/services/authService.ts
> Fix: #275 로그아웃시 Access Token이 포함되도록 수정

- .github/workflows/deploy.yaml
> Fix: #288 Github Actions AWS 배포 스크립트 환경변수명 수정
