GU-99/grow-up-fe

src/components/sidebar/ListProject.tsx
src/components/sidebar/ListSidebar.tsx
src/layouts/ProjectLayout.tsx
src/types/ProjectType.tsx
src/types/project.tsx

#21 특정 프로젝트 관리 UI 작성
진주님 이번에 만든 공용 사이드바는 사용자 개인정보 수정 페이지와 모든 프로젝트 관리 페이지의 사이드바에서 사용할 수 있다고 생각합니다. 문제는 모든 프로젝트 관리 페이지의 팀 생성 버튼에 대한 부분을 ToDo 주석으로 남겨둔 상황이라 이후에 필요하실 때 추가적으로 정의해주셨으면 합니다.

UI: #21 ProjectLayout의 Sidebar를 공용 Sidebar로 추출

---

src/components/modal/project/CreateModalProject.tsx
src/components/modal/project/ModalProjectForm.tsx
src/components/modal/project/UpdateModalProject.tsx
src/components/modal/team/UpdateModalTeam.tsx
src/components/sidebar/ListTeam.tsx
src/layouts/page/TeamLayout.tsx
src/pages/team/TeamPage.tsx

#62 모든 프로젝트 관리 페이지 UI 작성
**팀 안에 프로젝트가 있을시 화면 예시**
**팀 안에 프로젝트가 없을시 화면 예시**

 UI: #62 모든 프로젝트 관리 페이지 중 팀/프로젝트가 있는 경우 UI 작성

---

src/components/modal/task/ModalTaskForm.tsx
src/layouts/ModalLayout.tsx
src/layouts/page/ProjectLayout.tsx
src/mocks/mockData.ts
src/services/projectService.ts
src/types/RoleType.tsx
src/types/TaskType.tsx
src/types/UserType.tsx

#63 할일 등록 모달 UI 작성 및 기능 개발
**수행자 목록 UI**
**사용 가능한 체크 마크**
수행자 권한(`ADMIN`, `LEADER`, `ASSIGNEE`) UI가 별로 이쁘지 않아서 간단한 이모티콘으로 변경해보는게 어떨까 생각해봤습니다. 문득 체스 마크를 권한 등급으로 표현해보는게 어떨까라는 생각이 들었어요. 세계적으로 유명한 게임이고 각 체스말들의 등급이 사용자에게 직관적으로 느껴지지 않을까 싶어요. 그래서 권한 부분을 체스 마크로 변경해보는게 어떨까요?

Feat: #63 수행자 목록 UI 추가 & 수행자 추가/삭제 기능 구현

---

src/components/common/RoleIcon.tsx
src/components/modal/task/ModalTaskForm.tsx
src/mocks/mockData.ts

#63 할일 등록 모달 UI 작성 및 기능 개발
1. [CSS Tooltip](https://www.w3schools.com/css/css_tooltip.asp)
**변경 전**
**변경 후**

Feat: #63 수행자 권한 표시를 아이콘으로 변경 & 아이콘 툴팁 설명 추가

---

src/components/sidebar/ListSidebar.tsx
src/layouts/page/ProjectLayout.tsx
src/layouts/page/SettingLayout.tsx
src/layouts/page/TeamLayout.tsx
src/mocks/mockData.ts
src/mocks/services/userServiceHandler.ts
src/pages/setting/TeamSettingPage.tsx
src/services/userService.ts
src/types/TeamType.tsx

#72 유저 정보 설정 페이지 팀 설정 UI 구현
가입현황
대기현황

UI: #72 유저 정보 설정 페이지 팀 설정 UI 구현

---

src/components/common/CustomMarkdown.tsx

- close #90 
이전에는 markdown 문자열을 `\n`문자를 기준으로 분리하고, 빈 문자열이 등장하는 구간을 의도적인 개행 라인으로 판정하여 `<br />` 태그로 치환하도록 했습니다. 문제는 이 처리 과정이 코드 블록 내부의 개행 라인에도 영향을 줬습니다. 이를 해결하기 위해 코드 블록의 시작과 끝 사이에 있는 문장에 대해서는 `<br />`을 치환하지 못하도록 처리를 추가하였습니다.
추가적으로 코드 블록의 시작과 끝을 알려주는 ` ``` ` 문자가 짝수로 떨어지냐 홀수로 떨어지냐는 중요한 문제가 아니었습니다. 처음에 저도 ` ``` ` 문자가 홀수로 떨어지면 마지막 ` ``` `은 코드블록을 충족하지 않아  예외적인 처리를 추가해야 한다고 생각했지만,  홀수로 존재하는 ` ``` `에 대해서도 코드 블록으로 인식하고 마크다운을 파싱하는 것을 확인했습니다. 때문에 특별한 분기 없이 처리할 수 있었습니다.
**처리 변경 전**
**처리 변경 후**

Fix: #90 마크다운 코드 블록 내 개행문자가 <br />로 치환되는 문제 해결

---

src/components/common/Spinner.tsx
src/components/modal/project-status/ModalProjectStatusForm.tsx
src/components/modal/task/ModalTaskForm.tsx
src/hooks/query/useProjectQuery.ts
src/layouts/page/ProjectLayout.tsx
src/mocks/services/projectServiceHandler.ts
src/services/projectService.ts

Feat: #109 프로젝트 목록 조회 기능 구현

---

src/components/modal/task/ModalTaskForm.tsx
src/hooks/query/useStatusQuery.ts
src/hooks/query/useTaskQuery.ts
src/mocks/mockHash.ts
src/mocks/services/taskServiceHandler.ts
src/pages/project/CalendarPage.tsx
src/pages/project/KanbanPage.tsx
src/services/taskService.ts
src/types/TaskType.tsx

- close #104 
React Query 참고자료
[공식문서: Optimistic Updates](https://tanstack.com/query/latest/docs/framework/react/guides/optimistic-updates#if-the-mutation-and-the-query-dont-live-in-the-same-component)
[공식문서: Filters](https://tanstack.com/query/latest/docs/framework/react/guides/filters#mutation-filters)
[공식문서: useMutation](https://tanstack.com/query/latest/docs/framework/react/reference/useMutation)
[공식문서: useMutationState](https://tanstack.com/query/latest/docs/framework/react/reference/useMutationState)
<details>
<summary>1. 일정 순서 변경을 반영했을 때, 네트워크 요청을 처리하는 동안 변경된 내용을 부드럽게 화면에 표현하기 위해 낙관적 UI를  고려했습니다.</summary>
```
낙관적 UI를 만드는 방법은 크게 2가지였습니다. 첫 번째는 useMutation의 isPending과
variables를 이용하여 mutation이 pending 상태일 때, mutationFn에 전달한 변수를 가져와
보여주는 …
```

Feat: #104 일정 순서 변경 API를 이용하여 칸반 보드 DnD로 일정의 순서를 변경하는 기능 구현

---

src/hooks/query/useStatusQuery.ts
src/mocks/services/statusServiceHandler.ts
src/pages/project/KanbanPage.tsx
src/services/projectService.ts
src/services/statusService.ts
src/services/taskService.ts
src/services/teamService.ts
src/types/ProjectStatusType.tsx

- close #105 
**상태 순서 변경 반영에 실패한 경우**
**상태 순서 변경 반영에 성공한 경우**

Feat: #105 상태 순서 변경 API를 이용하여 칸반 보드 DnD로 상태의 순서를 변경하는 기능 구현

---

src/components/modal/task/CreateModalTask.tsx
src/components/modal/task/ModalTaskForm.tsx
src/hooks/query/useTaskQuery.ts
src/mocks/services/taskServiceHandler.ts
src/services/taskService.ts

- close #114 
프로젝트 상태 정보가 잘못오는 상황은 의도적으로 이상한 데이터를 끼워서 요청하거나, 잘못된  처리로 저장된 요염된 데이터인 경우일 것 같아요. 어떤 상황이든 좋은 상황은 아닌 것 같은데, 어떤 에러 처리를 추가해야할지 고민입니다. 다른 분들은 어떻게 생각하시나요?
```ts
const getLastSortOrder = (statusId: ProjectStatus['statusId']) => {
const statusTask = statusTaskList.find((statusTask) => statusTask.statusId === Number(statusId));
if (!statusTask) {
toastError('선택하신 프로젝트 상태는 존재하지 않습니다. ');
throw Error('프로젝트 상태가 존재하지 않습니다.');
}
return statusTask.tasks.length + 1;
};
```

Feat: #114 일정 생성 API를 이용하여 일정 생성 기능 구현

---

src/components/user/auth-form/ProfileImageContainer.tsx
src/mocks/mockData.ts
src/pages/setting/UserSettingPage.tsx
src/pages/user/SignUpPage.tsx
src/services/authService.ts
src/stores/useStore.ts
src/types/UserType.tsx

Chore: #128 유저 정보 값 수정

---

src/components/modal/task/DetailModalTask.tsx
src/components/modal/task/ModalTaskForm.tsx
src/hooks/query/useTaskQuery.ts
src/mocks/mockData.ts
src/mocks/services/taskServiceHandler.ts
src/services/taskService.ts
src/types/AssigneeType.tsx
src/types/TaskType.tsx

Feat: #134 일정 수행자 조회 기능 추가

---

src/components/user/auth-form/FooterLinks.tsx
src/components/user/auth-form/SearchDataForm.tsx
src/components/user/auth-form/SearchResultSection.tsx
src/hooks/useEmailVerification.ts
src/layouts/AuthFormLayout.tsx
src/layouts/page/AuthLayout.tsx
src/mocks/services/authServiceHandler.ts
src/pages/user/SearchIdPage.tsx
src/pages/user/SearchPasswordPage.tsx
src/pages/user/SignInPage.tsx
src/services/authService.ts
src/services/axiosProvider.ts
src/types/UserType.tsx
src/utils/converter.ts

#137 아이디/비밀번호 찾기 기능 구현
<details>
<summary><b>Auth 관련 화면</b></summary>
</details>

Feat: #137 아이디/비밀번호 찾기 기능 구현

---

src/components/user/auth-form/FooterLinks.tsx
src/components/user/auth-form/SearchDataForm.tsx
src/components/user/auth-form/SearchResultSection.tsx
src/hooks/useEmailVerification.ts
src/mocks/mockData.ts
src/mocks/services/authServiceHandler.ts
src/pages/setting/UserAuthenticatePage.tsx
src/pages/user/SearchIdPage.tsx
src/pages/user/SearchPasswordPage.tsx
src/pages/user/SignUpPage.tsx
src/services/authService.ts
src/types/UserType.tsx

#142 이메일 인증 기능 구현
- 이메일 인증 코드의 일치 여부는 ID, PW 찾기 API 내부에서 확인되는 방식입니다. 인증번호가 일치하지 않을 시 서버에서는 401 에러를 반환합니다. 
- 401 에러 반환 시 유저에게 에러 발생 사실을 알려주어야 했기에, `handleVerificationError` 함수를 실행하도록 처리했습니다. 이 처리 때문에 현재 네트워크 코드가 지저분해 보이는데, `useAxios` 적용되면 수정 및 리팩토링하도록 하겠습니다.
-  `회원가입`, `비밀번호 변경 전 인증` 페이지의 이메일 인증은 해당 API를 작성하면서 적용하도록 하겠습니다!
- 추가: 에러 발생을 명시할 때, 토스트 + 입력 필드 setError 두 가지를 사용하고 있는데, 너무 번잡하다면 AI 리뷰대로 둘 중 하나를 삭제해도 좋을 것 같습니다. 다른 분들의 의견은 어떤지 궁금합니다🧐

Feat: #142 이메일 인증 기능 구현

---

src/components/common/AssigneeList.tsx
src/components/common/SearchUserInput.tsx
src/components/modal/task/ModalTaskForm.tsx
src/hooks/query/useProjectQuery.ts
src/hooks/useProjectContext.tsx
src/layouts/page/ProjectLayout.tsx
src/mocks/services/projectServiceHandler.ts
src/services/projectService.ts
src/types/UserType.tsx

Feat: #147 수행자 검색 API 변경으로 인한 수행자 검색 기능 수정

---

src/components/modal/task/UpdateModalTask.tsx
src/hooks/query/useTaskQuery.ts
src/mocks/services/taskServiceHandler.ts
src/services/taskService.ts

- close #150 
**수행자 추가 에러시 화면**
**수행자 추가 성공시 화면**

Feat: #150 일정 수정 모달 수행자 삭제 기능 구현

---

src/components/user/auth-form/SearchDataForm.tsx
src/constants/formValidationRules.ts
src/constants/settings.ts
src/mocks/mockData.ts
src/mocks/services/authServiceHandler.ts
src/pages/setting/UserAuthenticatePage.tsx
src/pages/setting/UserPasswordSettingPage.tsx
src/pages/setting/UserSettingPage.tsx
src/pages/user/SearchIdPage.tsx
src/pages/user/SearchPasswordPage.tsx
src/pages/user/SignUpPage.tsx
src/services/authService.ts
src/services/axiosProvider.ts
src/stores/useStore.ts
src/types/UserType.tsx

#146 비밀번호 변경 전 인증 페이지의 인증 로직 구현
만료시간을 6초로 설정한 뒤 테스트해보았습니다. 
- 아직 `이메일 인증 확인 API`가 만들어지지 않은 상태라 임의로 엔드포인트와 응답을 설정해서 기능을 구현했습니다.
- 새로고침 시 이메일 인증이 초기화되는 문제는 추후 새로고침 시 `isAuthenticated` 변수가 초기화되는 문제와 함께 따로 구현해 PR 올리도록 하겠습니다.
- authAxios를 사용하는 API가 401에러 코드를 응답으로 받으면, 리프레시 토큰 오류로 처리되어서 강제로 로그인 화면으로 이동하는 에러가 있었습니다. 해당 에러를 수정하기 위해 리프레시 토큰 만료 시 오류메시지를 체크하도록 설정해 놓았는데, 이 부분은 나중에 에러 핸들링 구현이 어느 정도 완료되면 조금 더 명확한 방식으로 에러 체킹을 하도록 변경하겠습니다.

Feat: #146 비밀번호 변경 전 인증 페이지의 인증 로직 구현

---

src/components/common/FileDropZone.tsx
src/components/modal/task/CreateModalTask.tsx
src/components/modal/task/ModalTaskForm.tsx
src/components/modal/task/UpdateModalTask.tsx
src/constants/mimeFileType.ts
src/constants/regex.ts
src/constants/settings.ts
src/hooks/query/useTaskQuery.ts
src/mocks/mockData.ts
src/mocks/mockHash.ts
src/mocks/services/taskServiceHandler.ts
src/services/taskService.ts
src/types/FileType.tsx
src/types/TaskType.tsx
src/utils/Validator.ts

- close #115 
1. [React Query 공식문서: mutateAsync](https://tanstack.com/query/latest/docs/framework/react/reference/useMutation)
2. [MSW 공식 문서: File uploads](https://mswjs.io/docs/recipes/file-uploads/)
3. [MDN: FormData](https://developer.mozilla.org/ko/docs/Web/API/FormData)
4. [MDN: Promise.allSettled](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)
5. [MDN: Blob](https://developer.mozilla.org/ko/docs/Web/API/Blob)
6. [MDN: File](https://developer.mozilla.org/ko/docs/Web/API/File)
7. [MDN: Common MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)
8. [iana: Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml)
MSW를 통해 파일 …

Feat: #115 일정 등록 모달의 파일 업로드 기능 구현

---

src/hooks/query/useProjectQuery.ts
src/hooks/query/useStatusQuery.ts
src/hooks/query/useTaskQuery.ts
src/hooks/query/useTeamQuery.ts
src/utils/queryKeyGenergator.ts

- close #173 
Query Key를 문제 없이 옮긴 것 같은데, 혹시 모르니 확인할 때 신경써서 봐주시면 감사하겠습니다🙇‍♂️

Refactor: #173 React Query의 Query Key 정리

---

src/components/common/FileDropZone.tsx
src/components/modal/task/UpdateModalTask.tsx
src/hooks/query/useTaskQuery.ts
src/mocks/services/taskServiceHandler.ts
src/services/taskService.ts

Feat: #167 일정 수정 모달의 일정 파일 삭제 기능 구현

---

src/mocks/services/statusServiceHandler.ts
src/mocks/services/taskServiceHandler.ts

Fix: #182 칸반 보드에서 일정 삭제 / 상태 삭제 후 순서 변경이 제대로 일어나지 않는 문제 해결

---

src/components/modal/task/DetailModalTask.tsx
src/hooks/useAxios.ts
src/mocks/mockData.ts
src/mocks/services/taskServiceHandler.ts
src/services/taskService.ts
src/types/SearchCallbackType.tsx
src/utils/fileNameParser.ts

- close #168 
**참고 자료**
1. [MSW: Responding with binary](https://mswjs.io/docs/recipes/responding-with-binary/#browser)
2. [Axios의 responseType 4가지 옵션: 다양한 응답 데이터 유형 다루기](https://jollyworker.co.kr/axios%EC%9D%98-responsetype-%EC%98%B5%EC%85%98-%EB%8B%A4%EC%96%91%ED%95%9C-%EC%9D%91%EB%8B%B5-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%9C%A0%ED%98%95-%EB%8B%A4%EB%A3%A8%EA%B8%B0/)
3. [MDN: ArrayBuffer](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)
4. [MDN: Blob: arrayBuffer() method](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer)
5. [MDN: transferable objects](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects)
6. [HTTP Header: …

Feat: #168 일정 파일 다운로드 기능 구현

---

src/components/modal/task/DetailModalTask.tsx
src/components/task/kanban/TaskItem.tsx
src/pages/project/CalendarPage.tsx
src/pages/project/KanbanPage.tsx

- close #188
이전에 타입 수정으로 인해 Calendar 페이지에서 타입 호환 문제가 있는 것 같습니다. 이는 다음 PR에서 처리하도록 하겠습니다.
**캘린더에서의 수정 모달 전환**
**칸반보드에서의 수정 모달 전환**

Feat: #188 일정 상세 모달 수정 버튼 기능 구현 (상세 모달 → 수정 모달 전환)

---

src/pages/project/CalendarPage.tsx
src/types/TaskType.tsx

Fix: #202 Calendar 컴포넌트 events 타입 호환 문제 해결

---

src/components/modal/ModalButton.tsx
src/components/modal/project-status/CreateModalProjectStatus.tsx
src/components/modal/project-status/UpdateModalProjectStatus.tsx
src/components/modal/project/CreateModalProject.tsx
src/components/modal/project/UpdateModalProject.tsx
src/components/modal/task/CreateModalTask.tsx
src/components/modal/task/DetailModalTask.tsx
src/components/modal/task/UpdateModalTask.tsx
src/components/modal/team/CreateModalTeam.tsx
src/components/modal/team/UpdateModalTeam.tsx
src/components/task/calendar/CustomEventWrapper.tsx
src/components/task/kanban/TaskItem.tsx
src/hooks/query/useTaskQuery.ts
src/pages/project/CalendarPage.tsx
src/pages/project/KanbanPage.tsx

- close #204 
캘린더 양식에서는 문제없이 수정이 가능하지만, 칸반 보드에서 문제가 되는 부분이 있습니다.
일정 수정 모달에서는 다음과 같이 크게 3가지 영역으로 나뉘어 개별적으로 일정 정보를 수정하고 있습니다.
```
1. 일정 상태, 일정명, 기간(시작일/종료일), 일정 내용 수정 ⇒　일정 정보 수정 API
2. 수행자 추가/삭제 ⇒ 일정 수행자 추가 API, 일정 수행자 삭제 API
3. 파일 추가/삭제 ⇒ 일정 파일 추가 API, 일정 파일 삭제 API
```
이중에서 1번의 경우에서 특히 일정 상태를 수정할 때 발생하는 문제입니다. (일정명, 기간, 일정 내용 수정은 괜찮습니다.) 일정명, 기간, 일정 내용은 수정이 되더라도 TaskItem이라는 컴포넌트가 리렌더링이될 뿐 빠르게 언마운트 후 마운트하지 않습니다. 하지만 일정 상태를 수정하는 경우, 상태를 수정한 TaskItem에 한해서면 언마운트 후 마운트를 수행합니다. 때문에 일정 수정 모달의 showModal 정보가 초기화 되면서 모달 컴포넌트가 자동으로 사라집니다.
처음에는 react 상태(props, state), key 등의 영향으로 발생하는건가 고민해보았지만, 뚜렷히 원인을 찾을 수 없었고, react-beautiful-dnd 라이브러리의 issue를 확인하여 [비슷한 상황](https://github.com/atlassian/react-beautiful-dnd/issues/1650)을 겪은 내용을 찾았습니다.  해당 이슈도 dragend 이후 …

Feat: #204 일정 수정 모달에서 일정 상세 모달로 돌아가기 버튼 추가

---

src/components/common/PeriodDateInput.tsx
src/components/modal/task/ModalTaskForm.tsx
src/components/modal/task/UpdateModalTask.tsx
src/services/projectService.ts
src/utils/Validator.ts

- close #208 
현재 ERD 설계상으로는 DateTime으로 되어있지만, 실질적인 데이터는 연월일로 설정되기 때문에 Validation 로직을 일부 수정하였습니다. 또한 프로젝트 타입(Project)의 startDate와 endDate가 Date 타입으로 설정되어 있지만, 프로젝트 목록 조회시 네트워크로 받은 JSON 데이터를 파싱하여 변환하지 않아 여전히 문자열로 받는 문제가 있었습니다. 이를 해결하기 위해 프로젝트 목록 조회 API에 transformResponse 옵션을 추가하여 데이터 타입을 일치시키도록 수정했습니다.
**기간 설정에 따른 종료일 토글 자동 활성화/비활성화**
**기간 설정 중 종료일이 시작일보다 빠른 날짜를 설정하는 경우: 종료일 토글 비활성화 & 시작일과 일치**
**기간 설정중 종료일이 시작일과 같아지는 경우: 종료일 토글 비활성화**
**기간 설정중 종료일 설정 토글을 비활성화하는 경우: 종료일을 시작일과 일치**
**종료일 설정 토글이 비활성화 되어 있을 때 시작일을 이동하는 경우: 종료일을 항상 시작일과 일치**

Feat: #208 PeriodDateInput 컴포넌트 종료일 토글 자동 활성화 기능 추가

---

src/components/user/auth-form/LinkContainer.tsx
src/hooks/query/useUserQuery.ts
src/mocks/services/userServiceHandler.ts
src/pages/setting/UserSettingPage.tsx
src/pages/user/SignUpPage.tsx
src/services/userService.ts
src/stores/useStore.ts
src/types/UserType.tsx
src/utils/queryKeyGenerator.ts

- close #192
**성공**
**오류**
즉각적인 추가 / 삭제를 위해 추가적인 `링크 추가` 및 `링크 삭제` API를 고려했었는데,
수정 API만으로도 UI 변경 없이 구현이 되더라고요!
거기다 마감 기한이 다가온 상황이라, 우선은 추가적인 API 없이 수정 API만으로 작업을 진행했습니다😂
백엔드 담당자 분과도 추후 리팩토링 할 때 추가 API, 삭제 API를 추가할지 이야기를 한번 더 나눠보기로 대화가 되어서, 우선은 수정 API만으로 기능을 구현했습니다!

Feat: #192 링크 수정 기능 구현

---

src/mocks/mockAPI.ts
src/mocks/mockData.ts
src/mocks/services/taskServiceHandler.ts
src/mocks/services/userServiceHandler.ts
src/types/MockType.tsx
src/utils/Validator.ts

- close #196 
점진적으로 MSW 처리를 리팩토링할 예정이고, 이번 PR에서는 TaskService 관련 기능을 리팩토링했습니다.

Refactor: #196 MSW중 TaskService 관련 기능 리팩토링

---

src/components/common/Header.tsx
src/mocks/services/authServiceHandler.ts

- close #222 
**로그인 진행 시**
**로그인되지 않은 유저**
Zustand에 저장된 `isAutheticated` 속성을 이용해 헤더의 정보를 노출하도록 처리하였습니다!

Fix: #222 인증여부에 따라 헤더의 문구와 로그아웃 버튼 노출하도록 수정

---

src/components/user/auth-form/ProfileImageContainer.tsx
src/hooks/query/useUserQuery.ts
src/mocks/mockData.ts
src/mocks/services/userServiceHandler.ts
src/pages/setting/UserSettingPage.tsx
src/services/userService.ts
src/stores/useStore.ts
src/types/UserType.tsx
src/utils/queryKeyGenerator.ts

- close #211
**데이터 저장 결과 화면**
- 프론트측에서는 로그인과 함께 유저의 정보를 가져오고, 이후의 유저 정보 변경사항은 zustand 스토어의 유저 정보를 변경하는 방식으로 처리하고 있습니다.
- 유저 프로필 이미지에는 서버가 내려주는 UUID 정보가 저장되고, 이를 로그인과 동시에 받아오고 있습니다.
- 그런데 이미지 변경 시, 서버에서 저장하는 UUID의 정보를 프론트측에서 알 수가 없기 때문에 변경된 이미지 UUID 정보를 zustand 스토어에 저장하는 데 어려움이 있는 상황입니다.😭 이미지 파일 때문에 유저 정보 조회 API를 한번 더 요청하는 것도 좀 과한 처리 같아서 우선 해당 내용은 주석 처리를 해두었으며, 적합한 해결 방법을 알게 된다면 다음 PR에 추가하도록 하겠습니다. (방법을 알고 계신다면 조언을 부탁 드립니다🙇‍♂️)

Feat: #211 유저 프로필 이미지 업로드 기능 구현

---

src/mocks/services/authServiceHandler.ts
src/mocks/services/userServiceHandler.ts
src/routes/AfterLoginRoute.tsx
src/routes/BeforeLoginRoute.tsx
src/services/axiosProvider.ts

- close #228 
새로고침 시 zustand 내부의 인증값이 휘발되면서 로그인 페이지로 이동하는 현상이 발생하고 있습니다.
다른 분들 작업을 위해서 일단 작업한 부분만 올리고, 문제가 되는 내용은 내일 다시 PR을 올려 시정하도록 하겠습니다.
**추가 (수정)**
새로고침 시 `isAuthenticated`가 초기화되는 문제가 발생하였습니다.
로그인 후 영속적으로 유지되는 값인 `userInfo` 정보의 `userId`를 이용해 추가적인 체크를 하도록 하여 이를 수정했습니다.
보안적으로 완벽한 방법이 아니라 임시방편이기는 하지만 우선 새로고침 후에도 로그인 화면으로 이동되는 문제는 해결이 되었습니다.
보안적인 문제도 그렇고 현재의 로직은 `isAuthenticated`가 아니라 `userInfo`에 더 의존하고 있기 때문에 기존에 생각했던 로직과 달라진 점이 있습니다. 따라서 방법을 더 찾아보고 추가적인 수정이 필요할 것 같습니다.

Feat: #228 유저 인증을 위한 MSW 수정 및 페이지 라우트 인증 처리

---

src/components/common/Header.tsx
src/services/axiosProvider.ts

- close #236 
새로고침 시 `isAuthenticated`가 초기화되면서 헤더에 로그아웃 버튼 대신 로그인 버튼이 노출되는 이슈가 있었습니다.
이를 해결하고자 임시방편으로 이전 PR과 같이 영속 데이터인 userId를 체크하도록 코드를 추가했습니다.
추후 PR에서 새로고침 이슈 해결하면서 이 부분도 수정 진행하도록 하겠습니다!😆

Chore: #236 axiosProvider에서 JWT 더미데이터 삭제

---

src/components/modal/project/UpdateModalProject.tsx
src/hooks/query/useProjectQuery.ts
src/hooks/query/useTeamQuery.ts
src/mocks/services/projectServiceHandler.ts
src/utils/queryKeyGenerator.ts

Fix:#225 팀 쿼리 키 userId 추가 및 프로젝트 목록 조회 teamId null시 처리 추가

---

src/components/common/DescriptionTextarea.tsx
src/components/common/PeriodDateInput.tsx
src/components/modal/project/CreateModalProject.tsx
src/components/modal/project/ModalProjectForm.tsx
src/components/modal/team/ModalTeamForm.tsx
src/components/modal/team/UpdateModalTeam.tsx
src/constants/formValidationRules.ts
src/constants/role.ts
src/hooks/query/useProjectQuery.ts
src/hooks/query/useTeamQuery.ts
src/mocks/mockAPI.ts
src/mocks/mockData.ts
src/mocks/services/projectServiceHandler.ts
src/mocks/services/teamServiceHandler.ts
src/pages/project/CalendarPage.tsx
src/pages/team/TeamPage.tsx
src/services/projectService.ts
src/types/ProjectType.tsx
src/utils/Validator.ts

Feat: #200 프로젝트 생성

---

src/components/common/StatusRadio.tsx
src/components/modal/task/ModalTaskForm.tsx
src/layouts/page/ProjectLayout.tsx

Fix: #238 등록된 프로젝트 상태가 없을 때, 일정 등록을 시도하면 발생하는 문제 해결

---

src/components/modal/project-status/UpdateModalProjectStatus.tsx
src/components/modal/task/DetailModalTask.tsx
src/components/modal/task/ModalTaskForm.tsx
src/components/modal/task/UpdateModalTask.tsx
src/hooks/query/useTaskQuery.ts
src/utils/extractNameList.ts

Refactor: #243 전체 일정 조회에서 단일 일정 조회 로직 분리

---

src/components/modal/project/ModalProjectForm.tsx
src/components/modal/project/UpdateModalProject.tsx
src/components/modal/task/ModalTaskForm.tsx
src/components/modal/task/UpdateModalTask.tsx
src/components/modal/team/ModalTeamForm.tsx
src/components/modal/team/UpdateModalTeam.tsx
src/constants/formValidationRules.ts
src/hooks/query/useProjectQuery.ts
src/hooks/query/useTeamQuery.ts
src/hooks/useProjectContext.tsx
src/layouts/page/ProjectLayout.tsx
src/utils/extractNameList.ts

* close #241 
프로젝트 이름 , 설명 , 기간 UI
프로젝트 팀원 UI
프로젝트 기간 시작일 종료일 가져오는 모습

UI: #241 프로젝트 수정 UI 구현

---

src/components/modal/project/UpdateModalProject.tsx
src/components/modal/team/UpdateModalTeam.tsx
src/hooks/query/useProjectQuery.ts
src/mocks/services/projectServiceHandler.ts
src/services/projectService.ts

Feat: #246 프로젝트 수정 기능 구현

---

.gitignore
package.json

- close #258 
**mkcert**
1. [mkcert](https://github.com/FiloSottile/mkcert?tab=readme-ov-file)
2. [mkcert - localhost를 https 환경으로 만들기](https://yung-developer.tistory.com/112)
3. [Next.js, React(vite.js) 로컬 개발 환경 https 적용하기](https://2yh-develop4jeon.tistory.com/88)
**윈도우 패키지 매니저**
1. [윈도우 패키지 매니저 Scoop 설치하기](https://dmowld.tistory.com/32)
2. [Scoop installer](https://github.com/ScoopInstaller/Install#readme)
`mkcert - localhost를 https 환경으로 만들기` 블로그와 `Next.js, React(vite.js) 로컬 개발 환경 https 적용하기` 블로그를 참고하여 로컬에서 https를 인증하는 방법 알아봤습니다.  블로그 내용과 달랐던 점은 webpack을 이용하여 인증서를 설정하거나, vite.config.js 파일의 defineConfig를 통해 https 설정을 추가하지 않는다는 점입니다.
저희는 staging 환경용으로  build를 하고, 만들어진 정적 파일을 serve 라이브러리를 통해 로컬에서 배포하여 테스트 하고 있습니다. 이때 vite를 통해 번들링 하고 있고, …

Config: #258 스테이징 환경에 https 설정 적용

---

.github/workflows/vitest.yaml
package.json

- close #269 
**참고자료**
1. [Lean X in Y minutes YAML](https://learnxinyminutes.com/docs/yaml/)
2. [Inpa 블로: YAML 개념 & 문법 마스터하기](https://inpa.tistory.com/entry/YAML-%F0%9F%93%9A-yaml-%EA%B0%9C%EB%85%90-%EB%AC%B8%EB%B2%95-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-%F0%9F%92%AF-%EC%B4%9D%EC%A0%95%EB%A6%AC)
3. [JSON to YAML](https://www.bairesdev.com/tools/json2yaml/)
4. [Github Docs: Github Actions](https://docs.github.com/ko/actions)
5. [Github Marketplace](https://github.com/marketplace)
`main`과 `develop` 브랜치로 pull request를 작성했을 때 동작하도록 작성했고, paths 필터를 이용하여 src 하위 파일 중 변경이 일어났을 경우에만 실행하도록 제한했습니다. `opened`, `reopened`, `synchronize`는 default 값이고, 추가적으로 `ready_for_review` 타입을 추가하여 draft 상태에서 review 상태로 전환되었을 때도 동작하도록 했습니다.
if 조건절을 이용하여 draft 상태가 아닌 경우, 즉 …

Config: #269 Github Actions를 통해 테스트 통과 여부 검사 설정

---

src/stores/useStore.ts

- close #266 
토큰 만료 확인 및 재발급을 5초 주기로 설정한 뒤 테스트하였습니다.
기존에는 setTimeout으로 인한 액세스 토큰 기간 만료 문제를 해결해야 한다고 생각하고 수정을 진행했습니다.
하지만 액세스 토큰 만료 시 새로운 액세스 토큰을 요청할 때 서버에서 만료 시간 역시 새로 받아오기 때문에, 서버와 액세스 토큰 유지 기간을 동기화하기 위해서는 프론트에서 setTimeout으로 체크 중인 만료 시간 역시 초기화하는 게 맞다는 생각이 들었습니다. 따라서 만료 문제는 따로 처리할 필요가 없었기에 기존 로직을 그대로 유지했습니다.😂
대신 대기 상태에서 액세스 토큰 만료기간이 끝나 액세스 토큰이 자연 휘발될 시 새로운 액세스 토큰 요청을 보내고, 새로운 액세스 토큰을 잘 받아오는지 테스트를 진행했습니다. 
기존 로직에 setTimeout으로 인해 `isAuthenticated` 변수가 초기화되는 문제가 존재해서 이를 처리했습니다. 
(`isAuthenticated` 변수는 로그인 내내 true로 유지되어야 하는 변수이므로, setTimeout으로 인한 토큰 만료 시에도 true 값을 유지해야 합니다.)
테스트 결과, 기존에 발생했던 
- 로그아웃 문제 
- 대기 상태의 토큰 만료로 인한 repatch API 요청 실패 에러
이 두 문제도 해결된 것 같은데 혹시 모르니 확인 한번만 부탁드립니다!

Fix: #266 AT 기간 만료 시 로직 수정

---

.github/workflows/deploy.yaml

Config: #285 소셜 로그인 리다이렉트 URL 설정 & checkout 브랜치 명시
